services:
  database:
    image: mongo
    restart: always
    volumes:
     - "./mongo_db:/data/db"
     - "./mongo_configdb:/data/configdb"

  api:
    build:
      context: ./API-Moba
      dockerfile: Dockerfile
      args:
        - "DATABASE_HOST=database"
        - "DATABASE_NAME=MobaCup_Production"
    depends_on:
      - database
    ports:
     - "81:81"
    restart: always
  
  admin:
    build: ./admin-moba
    depends_on:
      - api
    ports:
      - "83:80"
    restart: always

  client:
    build: ./moba
    depends_on:
      - api
    ports:
      - "82:80"
    restart: always
